[build]
  publish = "dist"
  command = "bundle exec jekyll build --config jekyll.yml"

[build.environment]
  JEKYLL_ENV = "development"
  BUNDLE_WITHOUT = "development"
  NODE_OPTIONS = "--max_old_space_size=8192"
  MISE_DISABLE_TOOLS = "python"  # Prevent mise from installing Python based on Netlify's PYTHON_VERSION

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "preview"

[dev]
  # netlify automatically figures out and starts the framework, which in our case
  # is vite
  autoLaunch = false
  port = 7777
  targetPort = 3000

[[redirects]]
  from = "/fixtures/*"
  to = "/spec/fixtures/:splat"
  status = 200

[[headers]]
  for = "/fixtures/*"
  [headers.values]
    Cache-Control = "no-cache"
