name: Lint and test tools
on:
  push:
    branches: [master]
    paths: [tools/**]
  pull_request:
    paths: [tools/**]
jobs:
  lint-and-test-tools:
    name: Lint and test tool scripts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Shellcheck
        run: mise shellcheck
      - name: Run tool tests
        run: mise test:tools
