name: Lint and test tools
on:
  push:
    branches: [master]
    paths: [tools/**]
  pull_request:
    paths: [tools/**]
jobs:
  lint-and-test-tools:
    name: Lint and test tool scripts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Shellcheck
        run: mise shellcheck
      - name: Run tool tests
        run: mise test:tools
