name: Test tools
on:
  push:
    branches: [master]
    paths: [tools/**]
  pull_request:
    paths: [tools/**]
jobs:
  test-tools:
    name: Test tool scripts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tool tests
        run: mise test:tools
